### ISSUE TITLE
Can't git clone

### ISSUE THREAD

**Issue by moumitaTora** [aws-samples/mlops-sagemaker-github-actions#10]
I have succesfully created the organizational template and a sagemaker project using the template. However when I try to git clone, the following error occurs- Cloning into 'MY-PRIVATE-REPO'... fatal: unable to access '[https://codestar-connections.us-east-1.amazonaws.com/git-http/123456789/us-east-1/UNIQUE-ID/Private-repo.git/ ](https://codestar-connections.us-east-1.amazonaws.com/git-http/123456789/us-east-1/UNIQUE-ID/Private-repo.git/)': The requested URL returned error: 403. I have set up codestar connection, IAM policies and github personal access token but unable to resolve the issue. Also followed this https://pooya.io/how-to-access-github-and-bitbucket-using-aws-codestar/ as mentioned in the other closed issue. Any help would be greatly appreciated! Thanks

**Comment by pooyavahidi** [comment]
Hi @moumitaTora,
As you suggested (403 error), this is a permission issue somewhere which needs a bit of troubleshooting. If you have followed the steps in the blog, you should have the access. One other common place that I saw this problem solved was at the GitHub side. You need to give permission to the AWS app to access your repo. https://docs.github.com/en/apps/using-github-apps/authorizing-github-apps

**Comment by moumitaTora** [comment]
Thank you for your response. I have been trying yo attach the codestar policy (mentioned at the end of this blog https://pooya.io/how-to-access-github-and-bitbucket-using-aws-codestar/) to the role SageMakerGithubWorkflowTriggerLambdaExecutionRole that gets created when I create a new project. Should I be adding it somewhere else?
