### ISSUE TITLE
iam:GetRole issue of AmazonSageMakerServiceCatalogProductsLaunchRole

### ISSUE THREAD

**Issue by yuchenyeh-kt** [aws-samples/mlops-sagemaker-github-actions#4]
Hi,

I am able to get into Create Project via the newly created Organization template - build-deploy-github.
However, the project creation failed dut to this error "role/AmazonSageMakerServiceCatalogProductsLaunchRole/servicecatalog is not authorized to perform: iam:GetRole on resource: role SageMakerGithubWorkflowTriggerLambdaExecutionRole-0617865bc937 because no identity-based policy allows the iam:GetRole action".
<img width="680" alt="Screenshot 2023-09-08 at 10 57 50" src="https://github.com/aws-samples/mlops-sagemaker-github-actions/assets/77328353/16b3d2f2-1ddc-4e97-acbc-c4e7bbbbb646">

Could you please advise? Thanks

**Comment by pooyavahidi** [comment]
Hi @yuchenyeh-kt,
When you create a SageMaker project from a template, it uses the `AmazonSageMakerServiceCatalogProductsLaunchRole` role to launch the products of the service catalog. More details can be found [here](https://docs.aws.amazon.com/sagemaker/latest/dg/security-iam-awsmanpol-sc.html).

This role should have all the required permissions to launch your project. You can rectify this issue by adding the `iam:GetRole` permission to this role.

**Comment by yuchenyeh-kt** [comment]
@pooyavahidi  Thanks for your reply. The policy "AmazonSageMakerAdmin-ServiceCatalogProductsServiceRolePolicy" used by AmazonSageMakerServiceCatalogProductsLaunchRole is aws-managed. Since aws-managed policies cannot be edited, how do I rectify this issue?

**Comment by pooyavahidi** [comment]
Hi @yuchenyeh-kt,
Yes, the policy is managed. However, you can simply create a new custom policy (or choose an existing one) with the required permissions and add it to the AmazonSageMakerServiceCatalogProductsLaunchRole role.

**Comment by yuchenyeh-kt** [comment]
Thanks @pooyavahidi  - this is now resolved!

**Comment by pooyavahidi** [comment]
Close the issue as it has been resolved.
