### ISSUE TITLE
access issue with private github

### ISSUE THREAD

**Issue by richasuchak** [aws-samples/mlops-sagemaker-github-actions#5]
Hi, I have some issue. When I create a project with my private github repository, I see access error. But when I use public repo, it works fine. Can you help please?

**Comment by pooyavahidi** [comment]
Hi @richasuchak,
You need to setup a CodeStar connection for your private repo and then use the correct URL with the CodeStar connection unique Id. [Here](https://pooya.io/how-to-access-github-and-bitbucket-using-aws-codestar/) is a post for further details.

**Comment by pooyavahidi** [comment]
Resolved
