### ISSUE TITLE
Error getting project tags from "Build SageMaker Pipeline" - Build.yml Github Action

### ISSUE THREAD

**Issue by yuchenyeh-kt** [aws-samples/mlops-sagemaker-github-actions#6]
Hi,

I am getting an error when running the build.yml github action.

Error getting project tags: An error occurred (ValidationException) when calling the ListTags operation: 1 validation error detected: Value '' at 'resourceArn' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:aws[a-z-]*:sagemaker:[a-z0-9-]*:[0-9]{12}:.+

![image](https://github.com/aws-samples/mlops-sagemaker-github-actions/assets/77328353/80288551-7810-4fb4-952e-05a282ae4cd0)

Also, it seems that SAGEMAKER_PROJECT_ARN is also not declared in the build.yml.

![image](https://github.com/aws-samples/mlops-sagemaker-github-actions/assets/77328353/48fb586e-93ca-4b6b-99f9-a507baabb469)

Please advise on how to fix this issue. Thanks!

**Comment by pooyavahidi** [comment]
Hi @yuchenyeh-kt, thanks for pointing this out. The environment variable has now been added to the run command. Although this error was not a stopping error, and the GitHub Action would be executed successfully.
