### ISSUE TITLE
Getting error related to s3 access for lambda

### ISSUE THREAD

**Issue by moumitaTora** [aws-samples/mlops-sagemaker-github-actions#9]
While trying to create a project using the custom template, I get the error

Resource handler returned message: "Your access has been denied by S3, please make sure your request credentials have permission to GetObject for my-bucket/lambda-github-workflow-trigger.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied (Service: Lambda, Status Code: 403, Request ID: ##)" (RequestToken: ###, HandlerErrorCode: AccessDenied)

I am unable to figure out which role should I add the S3 GetObject policy to?

**Comment by pooyavahidi** [comment]
Hi @moumitaTora,
The execution role by default is this `AmazonSageMakerServiceCatalogProductsLaunchRole`

**Comment by moumitaTora** [comment]
solved
